import { Project, Activity, ActivityDependency, User, UserRole } from '@/types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Urban Road & Drainage Improvement',
    location: 'Central Business District, Zone A',
    baselineEndDate: new Date('2026-09-15'),
    currentEndDate: new Date('2026-09-18'),
    overallStatus: 'AT_RISK',
    budget: 50000000,
  },
];

export const MOCK_USERS: Record<UserRole, User> = {
  SITE_ENGINEER: {
    id: 'eng-1',
    name: 'Amit Sharma',
    email: 'amit.sharma@projectpulse.ai',
    role: 'SITE_ENGINEER',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amit',
  },
  CONTRACTOR: {
    id: 'con-1',
    name: 'BuildRight Infra Ltd',
    email: 'contact@buildright.com',
    role: 'CONTRACTOR',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BuildRight',
  },
  GOV_OFFICIAL: {
    id: 'gov-1',
    name: 'Rajesh Kumar',
    email: 'r.kumar@nhai.gov.in',
    role: 'GOV_OFFICIAL',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
  },
  CITIZEN: {
    id: 'cit-1',
    name: 'Suresh Iyer',
    email: 'suresh.iyer@gmail.com',
    role: 'CITIZEN',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Suresh',
  },
};

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    projectId: 'proj-1',
    code: 'WBS-1.1',
    name: 'Site Survey & Utility Mapping',
    plannedStart: new Date('2026-05-01'),
    plannedFinish: new Date('2026-05-15'),
    actualStart: new Date('2026-05-01'),
    actualFinish: new Date('2026-05-14'),
    baselineDuration: 14,
    remainingFloat: 0,
    isCriticalPath: true,
    plannedPercentComplete: 100,
    actualPercentComplete: 100,
  },
  {
    id: 'act-2',
    projectId: 'proj-1',
    code: 'WBS-1.2',
    name: 'Excavation - Phase 1',
    plannedStart: new Date('2026-05-16'),
    plannedFinish: new Date('2026-06-10'),
    actualStart: new Date('2026-05-16'),
    actualFinish: new Date('2026-06-12'),
    baselineDuration: 25,
    remainingFloat: 2,
    isCriticalPath: true,
    plannedPercentComplete: 100,
    actualPercentComplete: 100,
  },
  {
    id: 'act-3',
    projectId: 'proj-1',
    code: 'WBS-1.3',
    name: 'Drainage Installation',
    plannedStart: new Date('2026-06-13'),
    plannedFinish: new Date('2026-08-30'),
    actualStart: new Date('2026-06-15'),
    baselineDuration: 78,
    remainingFloat: 1,
    isCriticalPath: true,
    plannedPercentComplete: 90,
    actualPercentComplete: 65,
  },
  {
    id: 'act-4',
    projectId: 'proj-1',
    code: 'WBS-1.4',
    name: 'Base Layer Compaction',
    plannedStart: new Date('2026-09-01'),
    plannedFinish: new Date('2026-09-10'),
    baselineDuration: 10,
    remainingFloat: 1,
    isCriticalPath: true,
    plannedPercentComplete: 0,
    actualPercentComplete: 0,
  },
  {
    id: 'act-5',
    projectId: 'proj-1',
    code: 'WBS-1.5',
    name: 'Pavement Work',
    plannedStart: new Date('2026-09-11'),
    plannedFinish: new Date('2026-09-20'),
    baselineDuration: 10,
    remainingFloat: 0,
    isCriticalPath: true,
    plannedPercentComplete: 0,
    actualPercentComplete: 0,
  },
  {
    id: 'act-6',
    projectId: 'proj-1',
    code: 'WBS-1.6',
    name: 'Road Marking & Signage',
    plannedStart: new Date('2026-09-21'),
    plannedFinish: new Date('2026-09-25'),
    baselineDuration: 5,
    remainingFloat: 0,
    isCriticalPath: true,
    plannedPercentComplete: 0,
    actualPercentComplete: 0,
  },
];

export const MOCK_DEPENDENCIES: ActivityDependency[] = [
  { id: 'dep-1', predecessorId: 'act-1', successorId: 'act-2', type: 'FS', lag: 0 },
  { id: 'dep-2', predecessorId: 'act-2', successorId: 'act-3', type: 'FS', lag: 0 },
  { id: 'dep-3', predecessorId: 'act-3', successorId: 'act-4', type: 'FS', lag: 0 },
  { id: 'dep-4', predecessorId: 'act-4', successorId: 'act-5', type: 'FS', lag: 0 },
  { id: 'dep-5', predecessorId: 'act-5', successorId: 'act-6', type: 'FS', lag: 0 },
];
